version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres-pfs
    restart: unless-stopped
    environment:
      POSTGRES_USER: pfadmin
      POSTGRES_PASSWORD: StrongPassword123
      POSTGRES_DB: pfsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_pfs_data:/var/lib/postgresql/data

volumes:
  postgres_pfs_data:
